

training_pipeline_config:
  pipeline_name: visa
  artifact: artifact
  




data_ingestion_config:
  dataset_download_url: https://github.com/Shivan118/US-Visa-/blob/main/Visadataset%5B1%5D.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

